---
- hosts: all
  vars:
    user: vagrant
  user: "{{ user }}"
  tasks:
    ##
    # Apt package installation of required software.
    #
    - name: Update APT package cache
      tags: common
      apt: update_cache=yes
      sudo: true

    - name: Install packages
      apt: pkg={{ item }} state=installed
      tags: common
      sudo: true
      with_items:
        - curl
        - nginx
        - python-apt
        - python-pycurl
        - vim

    ##
    # set up git
    #
    - name: git | Add git repo
      apt_repository: repo='ppa:git-core/ppa'
      tags: git
      sudo: true

    - name: git | Install packages
      apt: pkg={{ item }} state=latest update_cache=yes
      tags: git
      sudo: true
      with_items:
        - git

    ##
    # set up nginx
    #
    - name: nginx | Configure the default site
      sudo: true
      lineinfile:
        dest=/etc/nginx/sites-enabled/default
        regexp="^\s*root"
        line="  root /vagrant/;"

    - name: nginx | Restart the nginx server
      service: name=nginx state=restarted
      sudo: true

    ##
    # set up git
    #
    - name: git | Set default configs
      template:
        src=~/.gitconfig
        dest=~{{ user }}/.gitconfig
        owner={{ user }}
        group={{ user }}
        mode=0644

    ##
    # node.js installation (latest stable instead of Ubuntu's out-of-date one)
    #
    - name: Node.js | Package prerequisites for node.js
      action: apt pkg=python-software-properties state=installed
      tags: nodejs
      sudo: true

    - name: Node.js | Add the node.js PPA
      apt_repository: repo='ppa:chris-lea/node.js'
      tags: nodejs
      sudo: true

    - name: Node.js | Install nodejs and npm
      action: apt pkg={{ item }} state=latest update_cache=yes
      tags: nodejs
      sudo: true
      with_items:
        - nodejs

    ##
    # npm package installation
    #
    - name: npm | Install globally required packages
      npm: name={{ item }} state=present global=yes
      sudo: true
      with_items:
        - bower
        - grunt-cli

    - name: npm | Install locally required packages
      npm: path=/vagrant

    - name: bower | Install required javascript libraries
      command: bower install
        chdir=/vagrant

    ##
    # set up my environment
    #
    - name: vim | Copy parent .vimrc
      template:
        src=~/.vimrc
        dest=~{{ user }}/.vimrc
        owner={{ user }}
        group={{ user }}
        mode=0644

    ##
    # set up my environment
    #
    - name: bashrc | Set up the terminal
      get_url:
        url=https://raw2.github.com/erikwiffin/analytics-promises/config-files/bashrc
        dest=~{{ user }}/.bashrc
        force=yes

    - name: bashrc | Chown bashrc for the user
      file:
        path=~{{ user }}/.bashrc
        owner={{ user }}
        group={{ user }}
        mode=0644
